# Generated by Django 5.2.16 on 2026-09-15 11:42

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0030_item_add_restriction_target'),
    ]

    operations = [
        # The vector type must exist before the embedding column is created.
        VectorExtension(),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='keywords')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'db_table': 'drive_graph_topic',
            },
        ),
        migrations.CreateModel(
            name='ItemTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='topic_membership', to='core.item')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='graph.topic')),
            ],
            options={
                'verbose_name': 'Item topic',
                'verbose_name_plural': 'Item topics',
                'db_table': 'drive_graph_item_topic',
            },
        ),
        migrations.CreateModel(
            name='ItemChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('index', models.PositiveIntegerField(verbose_name='index')),
                ('text', models.TextField(verbose_name='text')),
                ('text_hash', models.CharField(db_index=True, max_length=64, verbose_name='text hash')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
                ('signature', models.JSONField(blank=True, default=list, verbose_name='signature')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.item')),
            ],
            options={
                'verbose_name': 'Chunk',
                'verbose_name_plural': 'Chunks',
                'db_table': 'drive_graph_chunk',
                'ordering': ('item', 'index'),
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='graph_chunk_embedding_hnsw', opclasses=['vector_cosine_ops'])],
                'constraints': [models.UniqueConstraint(fields=('item', 'index'), name='unique_chunk_index_per_item')],
            },
        ),
        migrations.CreateModel(
            name='ItemLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('weight', models.FloatField(verbose_name='weight')),
                ('kind', models.CharField(choices=[('semantic', 'Semantic'), ('lexical', 'Lexical'), ('copy', 'Copy'), ('folder', 'Folder')], max_length=16, verbose_name='kind')),
                ('surprising', models.BooleanField(default=False, verbose_name='surprising')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('evidence', models.TextField(blank=True, verbose_name='evidence')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_out', to='core.item')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_in', to='core.item')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'db_table': 'drive_graph_link',
                'indexes': [models.Index(fields=['target', 'kind'], name='drive_graph_target__b2e4ce_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'target', 'kind'), name='unique_link_per_kind'), models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='link_not_to_self')],
            },
        ),
    ]
