# Generated by Django 5.2.16 on 2026-09-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='automatic',
            field=models.BooleanField(default=False, verbose_name='automatic'),
        ),
    ]
