# Generated by Django 5.2.16 on 2026-09-15 23:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_item_add_restriction_target'),
        ('graph', '0002_topic_automatic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('state', models.CharField(choices=[('pending', 'Being analysed'), ('done', 'Analysed'), ('empty', 'No text found'), ('skipped', 'Nothing to analyse'), ('failed', 'Analysis failed')], max_length=16, verbose_name='state')),
                ('detail', models.TextField(blank=True, verbose_name='detail')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graph_index', to='core.item')),
            ],
            options={
                'verbose_name': 'Indexing state',
                'verbose_name_plural': 'Indexing states',
                'db_table': 'drive_graph_index',
            },
        ),
    ]
