# Generated by Django 5.2.16 on 2026-09-16 10:17

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_item_add_restriction_target'),
        ('graph', '0004_drop_topics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('vector', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'db_table': 'drive_graph_topic',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ItemTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('pinned', models.BooleanField(default=False, verbose_name='pinned')),
                ('score', models.FloatField(default=0.0, verbose_name='score')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.item')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='graph.topic')),
            ],
            options={
                'verbose_name': 'Item topic',
                'verbose_name_plural': 'Item topics',
                'db_table': 'drive_graph_item_topic',
                'ordering': ('-score',),
            },
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('creator', 'name'), name='unique_topic_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='itemtopic',
            constraint=models.UniqueConstraint(fields=('item', 'topic'), name='unique_item_per_topic'),
        ),
    ]
