# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):
    """The reading score a file has to reach to belong to a subject."""

    dependencies = [("graph", "0005_user_topics")]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="cut",
            field=models.FloatField(default=0.0, verbose_name="cut"),
        ),
    ]
