# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):
    """The question a subject judges an uploaded file with."""

    dependencies = [("graph", "0006_topic_cut")]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="question",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="question"),
        ),
    ]
